name: Build Zygisk Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDKs
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            11
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Use 17 for the SDK tools
          log-accepted-android-sdk-licenses: true

      - name: Build with Gradle (Forced JDK 11)
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64
        run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-mod-menu
          path: out/*
          
